FROM nginx:1.23.3

# Install git and Hugo
RUN apt-get update && \
    apt-get install -y git && \
    apt-get install -y hugo && \
    rm -rf /var/lib/apt/lists/*

# Clone the repository and its submodules
RUN git clone --recurse-submodules https://github.com/chazapis/hy548.git

# Build the website using Hugo
RUN cd hy548 && \
    git submodule update --init --recursive && \
    cd html && hugo -D
RUN cp -a hy548/html/public/. /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
